ERR_FILENAME = "Erro! '{filename}' é invalido. A extensão deve ser '.map'."
ERR_NOTFOUND = "Erro! Mapa '{filename}' não encontrado."
ERR_MAP = "Erro! Mapa inválido."
ERR_IMAGE = "Erro! Imagem '{image}' é inválida."
OPTION = "\nEscolha uma opção:\n1 - Gerar um Mapa Aleatório\n2 - Inserir um Mapa Manualmente\n\nDigite o número correspondente a opção desejada: "
CLEAR = "\033[H\033[J"
